---
- name: Install dropbear-initramfs
  apt:
    pkg:
      - dropbear
      - initramfs-tools
      - busybox

- name: ensure dropbear is disabled after boot
  lineinfile:
    path: /etc/default/dropbear
    regexp: '^NO_START='
    line: 'NO_START=1'

- name: Copy unlock script
  copy:
    src: "{{ role_path }}/files/crypt_unlock.sh"
    dest: /etc/initramfs-tools/hooks/crypt_unlock.sh
    owner: root
    group: root
    mode: "0750"

- name: Copy unlock script
  copy:
    src: "{{ role_path }}/files/cleanup.sh"
    dest: /etc/initramfs-tools/scripts/init-bottom/cleanup.sh
    owner: root
    group: root
    mode: "0750"

- name: Manage dropbear authorized keys
  authorized_key:
    user: root
    state: present
    key: "{{ item.value }}"
    path: /etc/dropbear-initramfs/authorized_keys
    manage_dir: false
  with_dict: "{{ remote_unlock_authorized_keys }}"
  notify: Update Initramfs

- name: configure initramfs-tools
  lineinfile:
    path: /etc/initramfs-tools/initramfs.conf
    regexp: '^IP='
    line: 'IP={{ remote_unlock_initramfs_conf_ip }}'
  notify: Update Initramfs
